name: 'Bug Report'
description: 'Report a bug or issue with AI File Cleanup'
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched for existing issues that describe my problem
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version of AI File Cleanup
          required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      options:
        - 1.0.0
        - 1.0.1
        - main branch
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Web Application
        - Desktop Application (Electron)
        - API Service
        - Model Worker Service
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: 'e.g., 18.17.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or console output
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: environment
    attributes:
      label: Additional Environment Info
      description: Any additional information about your environment
      placeholder: |
        - Browser version (if web app)
        - Available memory
        - File system type
        - Any relevant configuration

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here