# Render deployment configuration for Fastify API
services:
  - type: web
    name: ai-file-cleanup-api
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Set in Render dashboard with Neon connection string
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET  
        generateValue: true
      - key: PORT
        value: 10000  # Render default port
    healthCheckPath: /healthz